- platform: template
  sensors:
    power_consumption:
      value_template: '{{ is_state("group.powercontrol", "on") and is_state("group.mediacenter", "off") }}'
    garage_door:
      friendly_name: 'Garage Door'
      device_class: 'opening'
      value_template: '{{ is_state("cover.garage", "open") }}'
    car_presence:
      friendly_name: 'Car Presence'
      device_class: 'occupancy'
      value_template: '{{ states.cover.garage.attributes.distance_sensor > 40 and states.cover.garage.attributes.distance_sensor < 100 }}'

