- platform: template
  sensors:
    sensor.sabnzbd_binary_status:
      friendly_name: 'SAB Status'
      sensor_class: connectivity
      value_template:  >-
        {%- if is_state("sensor.sabnzbd_status", "Downloading") -%}
        On
        {%- else -%}
        Off
        {%- endif %}
      entity_id: sensor.sabnzbd_left

