- platform: rest
  name: Travis Build
  resource: https://api.travis-ci.org/repos/bliemli/home-assistant-config/cc.json?branch=master
  scan_interval: 60
  value_template: "{{ value_json.last_build_status|int(1) == 0 }}"

- platform: template
  sensors:
    power_consumption:
      value_template: '{{ is_state("group.powercontrol", "on") and is_state("group.mediacenter", "off") }}'
    garage_door:
      friendly_name: 'Garage Door'
      device_class: 'opening'
      value_template: '{{ is_state("cover.garage", "open") }}'
    car_presence:
      friendly_name: 'Car Presence'
      device_class: 'occupancy'
      value_template: '{{ states.cover.garage.attributes.distance_sensor > 40 and states.cover.garage.attributes.distance_sensor < 100 }}'
    roomba_bin:
      friendly_name: 'Roomba Bin'
      value_template: '{{ states.vacuum.bodesuri.attributes.bin_full }}'

