config:
frontend:
mobile_app:
ssdp:
zeroconf:
logbook:

homeassistant:
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_time_zone
  customize: !include customize.yaml

discovery:
  ignore:
  - sonos

http:
  base_url: !secret http_base_url

history:
  exclude:
    domains:
    - automation

hue:
  bridges:
  - host: !secret hue_host

media_player:
- platform: kodi
  name: Kodi
  host: !secret kodi_host
- platform: openhome

vacuum:
- platform: roomba
  name: Roomba
  host: !secret roomba_host
  username: !secret roomba_username
  password: !secret roomba_password

notify:
- platform: pushover
  name: pushover
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key

cover:
  platform: opengarage
  covers:
    garage:        
      name: Garage
      host: !secret opengarage_host
      device_key: !secret opengarage_device_key

sensor:
- platform: mfi
  host: !secret mfi_host
  username: !secret mfi_username
  password: !secret mfi_password
  ssl: true
  verify_ssl: false
  scan_interval: 3
  entity_namespace: mfi
- platform: template
  sensors:
    roomba_battery:
      friendly_name: "Roomba Battery"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('vacuum.bodesuri', 'battery_level') }}"
      icon_template: "{{ state_attr('vacuum.bodesuri', 'battery_icon') }}"

binary_sensor:
- platform: workday
  country: !secret workday_country
  province: !secret workday_province
- platform: template
  sensors:
    roomba_bin_full:
      friendly_name: "Roomba Bin Full"
      value_template: >-
        {{ state_attr('vacuum.bodesuri', 'bin_full') }}
    phono_standby:
      friendly_name: "Phono Standby"
      value_template: >-
        {{ float(states.sensor.mfi_phono.state) < 1 }}
    subwoofer_standby:
      friendly_name: "Subwoofer Standby"
      value_template: >-
        {{ float(states.sensor.mfi_subwoofer.state) < 3 }}
    wiiu_standby:
      friendly_name: "Wii U Standby"
      value_template: >-
        {{ float(states.sensor.mfi_wiiu.state) < 3 }}

input_select:
  mediacenter:
    options:
     - 'music'
     - 'movies'
     - 'tv'
     - 'wiiu'
     - 'gamecube'
     - 'nes'
     - 'off'

switch: !include switches.yaml
script: !include scripts.yaml
automation: !include automations.yaml
