homeassistant:
  name: home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

frontend:

http:
  base_url: !secret base_url

recorder:
  purge_interval: 1
  purge_keep_days: 7

history:
  exclude:
    domains:
    - automation
    entities:
    - binary_sensor.random_binary_sensor
    - sensor.random_sensor

logbook:
  exclude:
    entities:
    - binary_sensor.random_binary_sensor
    - sensor.random_sensor

updater:
  reporting: no

discovery:

sun:

device_tracker:
- platform: locative

hue:
  bridges:
  - host: !secret hue_host

logger:
  default: warn
  logs:
    urllib3.connectionpool: critical
    homeassistant.components.sensor.rest: critical

media_player:
- platform: kodi
  host: !secret kodi_host
  name: Kodi
- platform: openhome
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

vacuum:
- platform: roomba
  name: bodesuri
  host: !secret roomba_host
  username: !secret roomba_blid
  password: !secret roomba_password

ios:

notify:
- platform: pushover
  name: pushover
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key

binary_sensor: !include binary_sensors.yaml
cover: !include covers.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml

alert: !include alerts.yaml
group: !include groups.yaml
scene: !include scenes.yaml

input_number: !include input_numbers.yaml
input_select: !include input_selects.yaml
rest_command: !include rest_commands.yaml
script: !include scripts.yaml
automation: !include_dir_merge_list automation

