homeassistant:
  name: home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

frontend:
#http:
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key

config:

recorder:
  purge_days: 30

history:

updater:
  reporting: no

discovery:
sun:

light:
  platform: hue

logger:
  default: info
  logs:
    homeassistant.core: error
    homeassistant.components.http: error
    homeassistant.components.sensor: error
    homeassistant.components.switch: error

media_player:
- platform: kodi
  host: !secret kodi_host
  name: Kodi
- platform: openhome

notify:
- platform: pushover
  name: pushover
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key

binary_sensor: !include binary_sensors.yaml
cover: !include covers.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml

alert: !include alerts.yaml
group: !include groups.yaml
scene: !include scenes.yaml

input_boolean: !include input_booleans.yaml
shell_command: !include shell_commands.yaml
automation: !include_dir_merge_list automation

