homeassistant:
  name: home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

frontend:

recorder:
  purge_interval: 1
  purge_keep_days: 7

history:

updater:
  reporting: no

discovery:
sun:

device_tracker:
- platform: locative

light:
  platform: hue
  allow_hue_groups: false

logger:
  default: info
  logs:
    homeassistant.core: error
    homeassistant.components.http: error
    homeassistant.components.sensor: error
    homeassistant.components.switch: error

media_player:
- platform: kodi
  host: !secret kodi_host
  name: Kodi
- platform: openhome

vacuum:
- platform: roomba
  name: bodesuri
  host: !secret roomba_host
  username: !secret roomba_blid
  password: !secret roomba_password

camera:
- platform: generic
  name: Kirchberg A1 Richtung Bern
  still_image_url: http://www.tbamobcam.ch/tbastrecke/tba003/stb_cam34.jpg
  scan_interval: 600

ios:

notify:
- platform: pushover
  name: pushover
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key

binary_sensor: !include binary_sensors.yaml
cover: !include covers.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml

alert: !include alerts.yaml
group: !include groups.yaml
scene: !include scenes.yaml

input_select: !include input_selects.yaml
rest_command: !include rest_commands.yaml
automation: !include_dir_merge_list automation

