homeassistant:
  name: home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 20
  icon: mdi:home

frontend:
#http:
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key

recorder:
  purge_days: 30

history:

updater:
  reporting: no

discovery:
sun:

light:
  platform: hue

logger:
  default: error

media_player:
- platform: kodi
  host: !secret kodi_host
  name: Kodi

notify:
- platform: pushover
  name: pushover
  api_key: !secret pushover_api_key
  user_key: !secret pushover_user_key

group: !include groups.yaml
scene: !include scenes.yaml

automation: !include_dir_merge_list automation
input_boolean: !include input_booleans.yaml
shell_command: !include shell_commands.yaml

switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

