- platform: sabnzbd
  name: SAB
  api_key: !secret sabnzbd_api_key
  host: !secret sabnzbd_host
  monitored_variables:
  - 'current_status'
  - 'speed'
  - 'queue_remaining'

- platform: mfi
  host: !secret mfi_host
  username: !secret mfi_username
  password: !secret mfi_password
  ssl: true
  verify_ssl: false
  scan_interval: 3
  entity_namespace: mfi

- platform: template
  sensors:
    sab_left_gb:
      friendly_name: 'SAB Left'
      unit_of_measurement: 'GB'
      value_template: '{{ (states("sensor.sab_left") | float / 1024) | round(1) }}'
    active_media_players:
      friendly_name: 'Active Media Players'
      value_template: >
        {{ states.media_player
         | rejectattr('state', 'equalto', 'idle')
         | rejectattr('state', 'equalto', 'off')
         | rejectattr('entity_id', 'equalto', 'media_player.snuggery')
         | map(attribute ='entity_id')
         | join(', ')
        }}

