- alias: Amp Power On
  trigger:
    platform: template
    value_template: '{{ is_state("input_select.mediacenter", "music") or is_state("input_select.mediacenter", "movies") or is_state("input_select.mediacenter", "wiiu") or is_state("input_select.mediacenter", "nes") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_amp
- alias: Amp Standby
  trigger:
    platform: template
    value_template: '{{ is_state("input_select.mediacenter", "off") or is_state("input_select.mediacenter", "gamecube") or is_state("input_select.mediacenter", "tv") }}'
  action:
    service: media_player.turn_off
    data:
      entity_id: media_player.snuggery
- alias: Amp Mediacenter Off
  trigger:
    platform: state
    entity_id: media_player.snuggery
    to: 'off'
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state != "off" and not (is_state("input_select.mediacenter", "gamecube") or is_state("input_select.mediacenter", "tv")) }}'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mediacenter
      option: 'off'
- alias: Amp Power Off
  trigger:
    platform: template
    value_template: '{{ is_state("media_player.snuggery", "off") and (is_state("input_select.mediacenter", "off") or is_state("input_select.mediacenter", "gamecube") or is_state("input_select.mediacenter", "tv")) }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.mfi_amp
- alias: Amp Source Change
  trigger:
    platform: state
    entity_id: sensor.snuggery_source
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state != "none" }}'
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.mediacenter
      option: '{{ trigger.to_state.state }}'
- alias: Amp Source Phono
  trigger:
    platform: numeric_state
    entity_id: sensor.mfi_phono
    above: 1
  action:
  - wait_template: '{{ states.media_player.snuggery.state != "off" }}'
  - service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Phono"
- alias: Amp Source Kodi
  trigger:
    platform: state
    entity_id: input_select.mediacenter
    to: 'movies'
  action:
  - wait_template: '{{ states.media_player.snuggery.state != "off" }}'
  - service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Kodi"
- alias: Amp Source Wii U
  trigger:
    platform: state
    entity_id: input_select.mediacenter
    to: 'wiiu'
  action:
  - wait_template: '{{ states.media_player.snuggery.state != "off" }}'
  - service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Wii U"
- alias: Amp Source NES
  trigger:
    platform: state
    entity_id: input_select.mediacenter
    to: 'nes'
  action:
  - wait_template: '{{ states.media_player.snuggery.state != "off" }}'
  - service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: 'NES'

