- alias: "Media player paused/stopped"
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'idle'
  condition:
    condition: state
    entity_id: light.couch
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.paper_lamp

- alias: "Media player playing"
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'playing'
  condition:
    condition: state
    entity_id: light.couch
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.paper_lamp

