- alias: "Media player paused/stopped"
  trigger:
    platform: state
    entity_id: media_player.kodi
    from: 'playing'
    to: 'idle'
  condition:
    condition: state
    entity_id: light.sphere_lamp_left
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.signal_lamp

- alias: "Media player playing"
  trigger:
    platform: state
    entity_id: media_player.kodi
    from: 'idle'
    to: 'playing'
  condition:
    condition: state
    entity_id: light.sphere_lamp_left
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.signal_lamp
