- alias: Media player paused/stopped
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'idle'
  condition:
    condition: state
    entity_id: light.floor_lamp
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.mediacenter

- alias: Media player playing
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'playing'
  condition:
    condition: state
    entity_id: light.floor_lamp
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.mediacenter

- alias: Vacation Mode Evening Lights On
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - delay: '00:{{ states.sensor.random_sensor.state | int }}'
  - service: scene.turn_on
    entity_id: scene.snuggery_standard

- alias: Vacation Mode Evening Lights Off
  trigger:
    platform: time
    at: '23:00'
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - delay: '00:{{ states.sensor.random_sensor.state | int }}'
  - service: light.turn_off
    entity_id:
    - light.floor_lamp
    - light.mediacenter

- alias: Vacation Mode Morning Lights On
  trigger:
    platform: time
    at: '06:57'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    - condition: sun
      before: sunrise
  action:
  - service: scene.turn_on
    entity_id: scene.snuggery_standard

- alias: Vacation Mode Morning Lights Off
  trigger:
    platform: time
    at: '07:41'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    - condition: state
      entity_id: light.floor_lamp
      state: 'on'
  action:
  - delay: '00:{{ states.sensor.random_sensor.state | int }}'
  - service: light.turn_off
    entity_id:
    - light.floor_lamp
    - light.mediacenter

