- alias: "Media player paused/stopped"
  trigger:
    platform: state
    entity_id: media_player.kodi
    from: 'playing'
    to: 'idle'
  condition:
    condition: state
    entity_id: light.sphere_lamp_left
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.snuggery_movies_pause

- alias: "Media player playing"
  trigger:
    platform: state
    entity_id: media_player.kodi
    from: 'idle'
    to: 'playing'
  condition:
    condition: state
    entity_id: light.sphere_lamp_left
    state: 'on'
  action:
    service: scene.turn_off
    entity_id: scene.snuggery_movies_play

- alias: "Bedroom light timer"
  trigger:
    platform: event
    event_type: timer.finished
    event_data: 
      entity_id: timer.bedroom_sleep_timer
  action:
    service: light.turn_off
    entity_id: light.bedroom_lightstrip

