- alias: 'Update Available Notification'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.ios_bliemliphone7
    data_template:
      message: 'Home Assistant {{ trigger.to_state.state }} is available.'

- alias: 'Active media player visibility'
  trigger:
  - platform: state
    entity_id: sensor.active_media_players
  action:
  - service_template: >
      {% if trigger.to_state.state != '' %}
        group.set
      {% endif %}
    data_template:
      object_id: active_media_players
      visible: true
      entities: '{{ trigger.to_state.state }}'
  - service_template: >
      {% if trigger.to_state.state == '' %}
        group.set
      {% endif %}
    data:
      object_id: active_media_players
      visible: false

