- alias: 'Switch amp on'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "on") or is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_wiiu", "on") or is_state("input_boolean.mediacontrol_nesmini", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_amp

- alias: 'Switch on TV'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_tv", "on") or is_state("input_boolean.mediacontrol_wiiu", "on") or is_state("input_boolean.mediacontrol_gamecube", "on") or is_state("input_boolean.mediacontrol_nesmini", "on") }}'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.mfi_tv

- alias: 'Switch on phono'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_phono

- alias: 'Switch on subwoofer'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "on") or is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_wiiu", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_subwoofer

- alias: 'Switch Wii U on'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_wiiu", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_wiiu

- alias: 'Switch on NES mini'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_nesmini", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_nesmini

