- alias: 'Set amp into standby when not in use.'
  trigger:
    platform: state
    entity_id:
    - input_boolean.play_music
    - input_boolean.watch_kodi
    - input_boolean.play_wiiu
    - input_boolean.play_nesmini
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.play_music
      state: 'off'
    - condition: state
      entity_id: input_boolean.watch_kodi
      state: 'off'
    - condition: state
      entity_id: input_boolean.play_wiiu
      state: 'off'
    - condition: state
      entity_id: input_boolean.play_nesmini
      state: 'off'
  action:
    service: shell_command.oh_standby

- alias: 'Shut off amp when in standby.'
  trigger:
    platform: numeric_state
    entity_id: sensor.power_consumption_linn_majik_dsm
    below: 26
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.play_music
      state: 'off'
    - condition: state
      entity_id: input_boolean.watch_kodi
      state: 'off'
    - condition: state
      entity_id: input_boolean.play_wiiu
      state: 'off'
    - condition: state
      entity_id: input_boolean.play_nesmini
      state: 'off'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_linn_majik_dsm

- alias: 'Switch TV off if not in use.'
  trigger:
    platform: state
    entity_id:
    - input_boolean.watch_kodi
    - input_boolean.watch_tv
    - input_boolean.play_wiiu
    - input_boolean.play_gamecube
    - input_boolean.play_nesmini
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.watch_kodi
      state: 'off'
    - condition: state
      entity_id: input_boolean.watch_tv
      state: 'off'
    - condition: state
      entity_id: input_boolean.play_wiiu
      state: 'off'
    - condition: state
      entity_id: input_boolean.play_gamecube
      state: 'off'
    - condition: state
      entity_id: input_boolean.play_nesmini
      state: 'off'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_tv

- alias: 'Shut off subwoofer when in standby.'
  trigger:
    platform: numeric_state
    entity_id: sensor.power_consumption_bw_asw10cm
    below: 3
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.play_music
      state: 'off'
    - condition: state
      entity_id: input_boolean.watch_kodi
      state: 'off'
    - condition: state
      entity_id: input_boolean.play_wiiu
      state: 'off'
    - condition: state
      entity_id: input_boolean.play_nesmini
      state: 'off'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_bw_asw10cm

- alias: 'Shut off subwoofer when already in standby.'
  trigger:
    platform: state
    entity_id:
    - input_boolean.play_music
    - input_boolean.watch_kodi
    - input_boolean.play_wiiu
    - input_boolean.play_nesmini
    from: 'on'
    to: 'off'
  condition:
    condition: numeric_state
    entity_id: sensor.power_consumption_bw_asw10cm
    below: 3
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_bw_asw10cm

- alias: 'Shut off Wii U when in standby.'
  trigger:
    platform: numeric_state
    entity_id: sensor.power_consumption_wii_u
    below: 3
  condition:
    condition: state
    entity_id: input_boolean.play_wiiu
    state: 'off'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_wiiu

- alias: 'Shut off GameCube when in standby.'
  trigger:
    platform: numeric_state
    entity_id: sensor.power_consumption_gamecube
    below: 3
  condition:
    condition: state
    entity_id: input_boolean.play_gamecube
    state: 'off'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_gamecube

