- alias: 'Switch amp on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ "states.input_select.media_control.state" == "Music" or "states.input_select.media_control.state" == "Movies" or "states.input_select.media_control.state" == "Wii U" or "states.input_select.media_control.state" == "NES mini" }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_linn_majik_dsm

- alias: 'Switch TV on based on media setting.'
  trigger:
    platform: template
    value_template: '{{ "states.input_select.media_control.state" != "Off" and "states.input_select.media_control.state" != "Music" }}'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.power_state_tv

- alias: 'Switch subwoofer on based on media setting.'
  trigger:
    platform: template
    value_template: '{{ "states.input_select.media_control.state" == "Music" or "states.input_select.media_control.state" == "Movies" or "states.input_select.media_control.state" == "Wii U" or "states.input_select.media_control.state" == "NES mini" }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_bw_asw10cm

- alias: 'Switch Wii U on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ "states.input_select.media_control.state" == "Wii U" }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_wiiu

- alias: 'Switch GameCube on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ "states.input_select.media_control.state" == "GameCube" }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_gamecube

