- alias: 'Put amp into standby when not in use.'
  trigger:
    platform: template
    value_template: '{{ is_state("group.mediacenter", "off") or is_state("input_boolean.mediacontrol_gamecube", "on") }}'
  action:
    service: media_player.turn_off
    data:
      entity_id: media_player.snuggery

- alias: 'Shut amp off when in standby and not in use.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.power_consumption_linn_majik_dsm.state) < 24 and (is_state("group.mediacenter", "off") or is_state("input_boolean.mediacontrol_gamecube", "on") or is_state("input_boolean.mediacontrol_tv", "on")) }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_linn_majik_dsm

- alias: 'Switch TV off when not in use.'
  trigger:
    platform: template
    value_template: '{{ is_state("group.mediacenter", "off") or is_state("input_boolean.mediacontrol_music", "on") }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_tv

- alias: 'Shut off subwoofer when in standby.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.power_consumption_bw_asw10cm.state) < 3 and (is_state("group.mediacenter", "off") or is_state("input_boolean.mediacontrol_tv", "on") or is_state("input_boolean.mediacontrol_gamecube", "on")) }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_bw_asw10cm

- alias: 'Shut Wii U off when in standby.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.power_consumption_wii_u.state) < 3 and is_state("input_boolean.mediacontrol_wiiu", "off") }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_wiiu
      
- alias: 'Shut off GameCube when in standby.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.power_consumption_gamecube.state) < 3 and is_state("input_boolean.mediacontrol_gamecube", "off") }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_gamecube

