- alias: 'Switch amp on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "on") or is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_wiiu", "on") or is_state("input_boolean.mediacontrol_nesmini", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_linn_majik_dsm

- alias: 'Switch TV on based on media setting.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_tv", "on") or is_state("input_boolean.mediacontrol_wiiu", "on") or is_state("input_boolean.mediacontrol_gamecube", "on") or is_state("input_boolean.mediacontrol_nesmini", "on") }}'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.power_state_tv

- alias: 'Switch subwoofer on based on media setting.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "on") or is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_wiiu", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_bw_asw10cm

- alias: 'Switch Wii U on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_wiiu", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_wiiu

- alias: 'Switch GameCube on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_gamecube", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_gamecube

