- alias: 'Switch amp on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "on") or is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_wiiu", "on") or is_state("input_boolean.mediacontrol_nesmini", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_amp

- alias: 'Switch TV on based on media setting.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_tv", "on") or is_state("input_boolean.mediacontrol_wiiu", "on") or is_state("input_boolean.mediacontrol_gamecube", "on") or is_state("input_boolean.mediacontrol_nesmini", "on") }}'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.mfi_tv

- alias: 'Switch phono on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_phono

- alias: 'Switch subwoofer on based on media setting.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "on") or is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_wiiu", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_subwoofer

- alias: 'Switch Wii U on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_wiiu", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_wiiu

- alias: 'Switch NES mini on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_nesmini", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_nesmini

