- alias: 'Put amp into standby when not in use.'
  trigger:
    platform: template
    value_template: '{{ is_state("group.mediacenter", "off") or is_state("input_boolean.mediacontrol_gamecube", "on") }}'
  action:
    service: media_player.turn_off
    data:
      entity_id: media_player.snuggery

- alias: 'Shut amp off when in standby and not in use.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.mfi_amp.state) < 25 and (is_state("group.mediacenter", "off") or is_state("input_boolean.mediacontrol_gamecube", "on") or is_state("input_boolean.mediacontrol_tv", "on")) }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.mfi_amp

- alias: 'Shut phono off when not in use.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "off") }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.mfi_phono

- alias: 'Switch TV off when not in use.'
  trigger:
    platform: template
    value_template: '{{ is_state("group.mediacenter", "off") or is_state("input_boolean.mediacontrol_music", "on") }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.mfi_tv

- alias: 'Shut off subwoofer when in standby.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.mfi_subwoofer.state) < 3 and (is_state("group.mediacenter", "off") or is_state("input_boolean.mediacontrol_tv", "on") or is_state("input_boolean.mediacontrol_gamecube", "on")) }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.mfi_subwoofer

- alias: 'Shut Wii U off when in standby.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.mfi_wiiu.state) < 3 and is_state("input_boolean.mediacontrol_wiiu", "off") }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.mfi_wiiu
      
- alias: 'Shut off NES mini when not in use.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_nesmini", "off") }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.mfi_nesmini

