- alias: 'Switch amp on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_select.media_control", "Music") or is_state("input_select.media_control", "Movies") or is_state("input_select.media_control", "Wii U") or is_state("input_select.media_control", "NES") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_linn_majik_dsm

- alias: 'Switch TV on based on media setting.'
  trigger:
    platform: template
    value_template: '{{ not is_state("input_select.media_control", "Off") and not is_state("input_select.media_control", "Music") }}'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.power_state_tv

- alias: 'Switch subwoofer on based on media setting.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_select.media_control", "Music") or is_state("input_select.media_control", "Movies") or is_state("input_select.media_control", "Wii U") or is_state("input_select.media_control", "NES") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_bw_asw10cm

- alias: 'Switch Wii U on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_select.media_control", "Wii U") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_wiiu

- alias: 'Switch GameCube on based on media settings.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_select.media_control", "NGC") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.power_state_gamecube

