- alias: 'Put amp into standby when not in use.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_select.media_control", "Off") or is_state("input_select.media_control", "NGC") }}'
  action:
    service: shell_command.oh_standby

- alias: 'Shut amp off when in standby and not in use.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.power_consumption_linn_majik_dsm.state) < 26 and (is_state("input_select.media_control", "Off") or is_state("input_select.media_control", "NGC") or is_state("input_select.media_control", "TV")) }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_linn_majik_dsm

- alias: 'Switch TV off when not in use.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_select.media_control", "Off") or is_state("input_select.media_control", "Music") }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_tv

- alias: 'Shut off subwoofer when in standby.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.power_consumption_bw_asw10cm.state) < 3 and (is_state("input_select.media_control", "Off") or is_state("input_select.media_control", "TV") or is_state("input_select.media_control", "NGC")) }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_bw_asw10cm

- alias: 'Shut Wii U off when in standby.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.power_consumption_wii_u.state) < 3 and not is_state("input_select.media_control", "Wii U") }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_wiiu
      
- alias: 'Shut off GameCube when in standby.'
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.power_consumption_gamecube.state) < 3 and not is_state("input_select.media_control", "NGC") }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_gamecube

