- alias: 'Put amp into standby based on media setting.'
  trigger:
    platform: state
    entity_id: input_select.media_control
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.media_control
      state: 'Off'
    - condition: state
      entity_id: input_select.media_control
      state: GameCube
  action:
    service: shell_command.oh_standby

- alias: 'Shut amp off when going into standby.'
  trigger:
    platform: numeric_state
    entity_id: sensor.power_consumption_linn_majik_dsm
    below: 26
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.media_control
      state: 'Off'
    - condition: state
      entity_id: input_select.media_control
      state: GameCube
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_linn_majik_dsm

- alias: 'Shut amp off when already in standby.'
  trigger:
    platform: state
    entity_id: input_select.media_control
  condition:
    condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.power_consumption_linn_majik_dsm
      below: 26
    - condition: state
      entity_id: input_select.media_control
      state: 'Off'
    - condition: state
      entity_id: input_select.media_control
      state: GameCube
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_linn_majik_dsm

- alias: 'Switch TV off based on media setting.'
  trigger:
    platform: state
    entity_id: input_select.media_control
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.media_control
      state: 'Off'
    - condition: state
      entity_id: input_select.media_control
      state: Music
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_tv

- alias: 'Shut off subwoofer when going into standby.'
  trigger:
    platform: numeric_state
    entity_id: sensor.power_consumption_bw_asw10cm
    below: 3
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.media_control
      state: 'Off'
    - condition: state
      entity_id: input_select.media_control
      state: TV
    - condition: state
      entity_id: input_select.media_control
      state: GameCube
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_bw_asw10cm

- alias: 'Shut off subwoofer when already in standby.'
  trigger:
    platform: state
    entity_id: input_select.media_control
  condition:
    condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.power_consumption_bw_asw10cm
      below: 3
    - condition: state
      entity_id: input_select.media_control
      state: 'Off'
    - condition: state
      entity_id: input_select.media_control
      state: TV
    - condition: state
      entity_id: input_select.media_control
      state: GameCube
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_bw_asw10cm

- alias: 'Shut off Wii U when going into standby.'
  trigger:
    platform: numeric_state
    entity_id: sensor.power_consumption_wii_u
    below: 3
  condition:
    condition: template
    value_template: "{{ not is_state('input_select.media_control', 'Wii U') }}"
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_wiiu

- alias: 'Shut off Wii U when already in standby.'
  trigger:
    platform: numeric_state
    entity_id: input_select.media_control
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.power_consumption_wii_u
      below: 3
    - condition: template
      value_template: "{{ not is_state('input_select.media_control', 'Wii U') }}"
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_wiiu

- alias: 'Shut off GameCube when going into standby.'
  trigger:
    platform: numeric_state
    entity_id: sensor.power_consumption_gamecube
    below: 3
  condition:
    condition: template
    value_template: "{{ not is_state('input_select.media_control', 'GameCube') }}"
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_gamecube

- alias: 'Shut off GameCube when already in standby.'
  trigger:
    platform: numeric_state
    entity_id: input_select.media_control
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.power_consumption_gamecube
      below: 3
    - condition: template
      value_template: "{{ not is_state('input_select.media_control', 'GameCube') }}"
  action:
    service: switch.turn_off
    data:
      entity_id: switch.power_state_gamecube
