- alias: 'Delay presence detection state'
  trigger:
    platform: state
    entity_id: !secret device1
    to: 'pre_home'
    for:
      seconds: 15
  action:
    service: device_tracker.see
    data:
      dev_id: !secret device1_id
      location_name: 'home'

- alias: 'Translate presence detection state'
  trigger:
    platform: state
    entity_id: !secret device1
    to: 'not_pre_home'
  action:
    service: device_tracker.see
    data:
      dev_id: !secret device1_id
      location_name: 'not_home'

