- alias: 'Amp remote standby'
  trigger:
    platform: state
    entity_id: media_player.snuggery
    to: 'off'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.mediacenter
      option: 'off'

- alias: 'Amp remote source change'
  trigger:
    platform: state
    entity_id: sensor.snuggery_source
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.mediacenter
      option: '{{ trigger.to_state.state }}'

