- alias: 'Roomba schedule'
  trigger:
    platform: time
    at: '14:00:00'
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ states.group.all_devices.state != "home" }}'
  action:
    service: vacuum.start_pause
    entity_id: vacuum.bodesuri

- alias: 'Roomba base return'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: vacuum.bodesuri
    state: 'on'
  action:
    service: vacuum.return_to_base
    entity_id: vacuum.bodesuri

- alias: 'Roomba bad state notification'
  trigger:
    platform: template
    value_template: "{% if is_state_attr('vacuum.bodesuri', 'status', 'Charging') or is_state_attr('vacuum.bodesuri', 'status', 'Running') or is_state_attr('vacuum.bodesuri', 'status', 'End Mission') %}false{% else %}true{% endif %}"
  action:
    service: notify.pushover
    data:
      message: 'Roomba is {{ states.vacuum.bodesuri.attributes.status | lower }}.'

- alias: 'Roomba bin full notification'
  trigger:
    platform: state
    entity_id: binary_sensor.roomba_bin
    from: 'off'
    to: 'on'
  action:
    service: notify.pushover
    data:
      message: 'Roomba bin is full.'

