- alias: 'Switch source to TV based on media setting.'
  trigger:
    platform: state
    entity_id: input_select.media_control
    to: TV
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.philips_tv
      source: "Watch TV"

- alias: 'Switch source to amp based on media setting.'
  trigger:
    platform: state
    entity_id: input_select.media_control
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.media_control
      state: Movies
    - condition: state
      entity_id: input_select.media_control
      state: Wii U
    - condition: state
      entity_id: input_select.media_control
      state: NES
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.philips_tv
      source: "Linn Majik"

- alias: 'Switch source to GameCube based on media setting.'
  trigger:
    platform: state
    entity_id: input_select.media_control
    to: GameCube
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.philips_tv
      source: "GameCube"

