- alias: 'Phono consumes power'
  trigger:
    platform: numeric_state
    entity_id: sensor.mfi_phono
    above: 1
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Phono"

- alias: 'Music switch active'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "on") and not is_state("media_player.snuggery", "off") }}'
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Playlist"

- alias: 'Kodi switch active'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") and not is_state("media_player.snuggery", "off") }}'
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Kodi"

- alias: 'Wii U switch active'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_wiiu", "on") and not is_state("media_player.snuggery", "off") }}'
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Wii U"

- alias: 'NES switch active'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_nes", "on") and not is_state("media_player.snuggery", "off") }}'
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: 'NES'

