- alias: 'Switch source to phono if power consume is detected.'
  trigger:
    platform: numeric_state
    entity_id: sensor.mfi_phono
    above: 1
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Phono"

- alias: 'Switch source to Playlist based on media setting.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_music", "on") }}'
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Playlist"

- alias: 'Switch source to Kodi based on media setting.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") }}'
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Kodi"

- alias: 'Switch source to Wii U when activated.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_wiiu", "on") }}'
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "Wii U"

- alias: 'Switch source to NES mini when activated.'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_nesmini", "on") }}'
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.snuggery
      source: "NES mini"

