- alias: Subwoofer power on
  trigger:
    platform: template
    value_template: '{{ is_state("input_select.mediacenter", "music") or is_state("input_select.mediacenter", "movies") or is_state("input_select.mediacenter", "wiiu") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_subwoofer
- alias: Subwoofer power off
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.mfi_subwoofer.state) < 3 and (is_state("input_select.mediacenter", "off") or is_state("input_select.mediacenter", "tv") or is_state("input_select.mediacenter", "gamecube")) }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.mfi_subwoofer

