- alias: 'Switch source to phono if power consume is detected.'
  trigger:
    platform: numeric_state
    entity_id: sensor.power_consumption_phono
    above: 1
  action:
    service: shell_command.oh_phono

- alias: 'Switch source to Kodi when activated.'
  trigger:
    platform: state
    entity_id: input_boolean.watch_kodi
    from: 'off'
    to: 'on'
  action:
  - service: shell_command.oh_kodi
  - service: shell_command.oh_volume40
  - delay: 00:00:30
  - service: shell_command.oh_kodi
  - service: shell_command.oh_volume40

- alias: 'Switch source to Wii U when activated.'
  trigger:
    platform: state
    entity_id: input_boolean.play_wiiu
    from: 'off'
    to: 'on'
  action:
  - service: shell_command.oh_wiiu
  - delay: 00:00:30
  - service: shell_command.oh_wiiu

- alias: 'Switch source to NES mini when activated.'
  trigger:
    platform: state
    entity_id: input_boolean.play_nesmini
    from: 'off'
    to: 'on'
  action:
  - service: shell_command.oh_nesmini
  - delay: 00:00:30
  - service: shell_command.oh_nesmini

