- alias: Wii U power on
  trigger:
    platform: template
    value_template: '{{ is_state("input_select.mediacenter", "wiiu") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.mfi_wiiu
- alias: Wii U power off
  trigger:
    platform: template
    value_template: '{{ float(states.sensor.mfi_wiiu.state) < 3 and (is_state("input_select.mediacenter", "off") or not is_state("input_select.mediacenter", "wiiu")) }}'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.mfi_wiiu

